apiVersion: v1
kind: Service
metadata:
  name: {{ template "distributed-jmeter.fullname" . }}-master-service 
  labels:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    helm.sh/chart: {{ include "distributed-jmeter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
    app: jmeter-master
spec:
  # clusterIP: None
  ports:
    - port: 9270
      protocol: TCP
      #targetPort: 9270
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: master
